site_name: PDFFile
site_author: AJ
site_description: .A ZipFile like API for PDFs
theme:
  name: mkdocs
  color_mode: dark
  strict: true

plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      css_files:
        - style.css
  - search
  - mkapi
markdown_extensions:
  - smarty
  - toc:
      permalink: true
extra_css:
  - style.css
nav:
  - NEWS.md
  - API: $api/pdffile.***
