extra_css:
  - style.css
markdown_extensions:
  - smarty
  - toc:
      permalink: true
nav:
  - NEWS.md
  - API: $api/pdffile.***
plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      css_files:
        - style.css
  - search
  - mkapi
site_author: AJ
site_description: A ZipFile like API for PDFs
site_name: PDFFile
theme:
  color_mode: dark
  name: mkdocs
  strict: true
